services:
  - type: web
    name: finance-assistant
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: APP_NAME
        sync: false
      - key: ENV
        value: prod
      - key: SECRET_KEY
        sync: false
      - key: SESSION_COOKIE_NAME
        sync: false
      - key: ENABLE_DOCS
        sync: false
      - key: ENABLE_REDOC
        sync: false
      - key: DEMO_USERNAME
        sync: false
      - key: DEMO_PASSWORD
        sync: false
